<a href="https://colab.research.google.com/github/bishaarabdi1/artificial-intelligence-/blob/main/machine-learning/studentcleaneddata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

paratical

In [1]:
import pandas as pd

In [20]:

df= pd.read_csv("student_cleaning_practice_200_v2.csv")

In [21]:
df.head()

,student_id,name,age,gender,school,city,study_hours_per_day,attendance_percent,internet_access,parent_support,absences,exam_score,grade
0,STU034,Abdi Mohamed,19.0,Male,Bile Academy,Baidoa,4,87.0,No,No,3,69.0,C
1,STU086,Yusuf Yusuf,22.0,Male,Hodan School,Kismayo,5,87.0,No,No,0,98.0,A
2,STU057,Yusuf Hassan,18.0,Female,Hamar School,Baidoa,2,95.0,No,No,0,50.0,D
3,STU105,Hodan Yusuf,20.0,NaN,Bile Academy,Garowe,5,84.0,No,Yes,6,54.0,D
4,STU121,Ifrah Warsame,17.0,Male,Hamar School,Mogadishu,3,70.0,Yes,Yes,7,90.0,A

In [4]:

df.shape

(200, 1)

Day 2 EDA

In [22]:
new_df = df.copy()

In [23]:
new_df.isnull().sum()

student_id              0
name                    0
age                    12
gender                 10
school                  0
city                    8
study_hours_per_day     0
attendance_percent     11
internet_access         0
parent_support          0
absences                0
exam_score              8
grade                   0
dtype: int64

In [26]:

# filnna()
new_df["age"].median()

19.0

In [27]:
new_df["age"].fillna(new_df["age"].median()).astype(int)

0      19
1      22
2      18
3      20
4      17
       ..
195    22
196    19
197    17
198    16
199    22
Name: age, Length: 200, dtype: int64

In [43]:
new_df["gender"].mode()

0    Female
Name: gender, dtype: object

In [56]:
new_df["gender"]=new_df["gender"].fillna(new_df["gender"].mode()[0])

In [62]:
new_df["attendance_percent"].median()

82.5

In [63]:
new_df["attendance_percent"].fillna(new_df["attendance_percent"].median()).astype(int)

0      87
1      87
2      95
3      84
4      70
       ..
195    74
196    82
197    93
198    95
199    76
Name: attendance_percent, Length: 190, dtype: int64

In [37]:
new_df["exam_score"].median()

74.0

In [38]:
new_df["exam_score"].fillna(new_df["exam_score"].median()).astype(int)

0      69
1      98
2      50
3      54
4      90
       ..
195    49
196    92
197    88
198    53
199    98
Name: exam_score, Length: 200, dtype: int64

In [50]:
new_df.duplicated().sum()

np.int64(0)

In [54]:
new_df.head()

,student_id,name,age,gender,school,city,study_hours_per_day,attendance_percent,internet_access,parent_support,absences,exam_score,grade
0,STU034,Abdi Mohamed,19.0,Male,male,Baidoa,4,87.0,No,No,3,69.0,C
1,STU086,Yusuf Yusuf,22.0,Male,male,Kismayo,5,87.0,No,No,0,98.0,A
2,STU057,Yusuf Hassan,18.0,Female,female,Baidoa,2,95.0,No,No,0,50.0,D
3,STU105,Hodan Yusuf,20.0,Female,female,Garowe,5,84.0,No,Yes,6,54.0,D
4,STU121,Ifrah Warsame,17.0,Male,male,Mogadishu,3,70.0,Yes,Yes,7,90.0,A

In [ ]:
new_df["gender"] = new_df["gender"].str.strip().str.lower().map({
    "male": "Male",
    "female": "Female"
})

In [53]:
new_df["gender"].value_counts()

gender
Female      104
Male         81
female        3
 Male         1
 Female       1
Name: count, dtype: int64

In [55]:
new_df.head()

,student_id,name,age,gender,school,city,study_hours_per_day,attendance_percent,internet_access,parent_support,absences,exam_score,grade
0,STU034,Abdi Mohamed,19.0,Male,male,Baidoa,4,87.0,No,No,3,69.0,C
1,STU086,Yusuf Yusuf,22.0,Male,male,Kismayo,5,87.0,No,No,0,98.0,A
2,STU057,Yusuf Hassan,18.0,Female,female,Baidoa,2,95.0,No,No,0,50.0,D
3,STU105,Hodan Yusuf,20.0,Female,female,Garowe,5,84.0,No,Yes,6,54.0,D
4,STU121,Ifrah Warsame,17.0,Male,male,Mogadishu,3,70.0,Yes,Yes,7,90.0,A

In [64]:
new_df.loc[new_df["name"] == "Yusuf Yusuf", "gender"] = "Male"

In [65]:
new_df[new_df["name"] == "Yusuf Yusuf"]

,student_id,name,age,gender,school,city,study_hours_per_day,attendance_percent,internet_access,parent_support,absences,exam_score,grade,attendance_percent\t
1,STU086,Yusuf Yusuf,22.0,Male,male,Kismayo,5,87.0,No,No,0,98.0,A,87.0
29,STU038,Yusuf Yusuf,20.0,Male,female,Kismayo,6,78.0,No,Yes,2,63.0,C,78.0
54,STU033,Yusuf Yusuf,20.0,Male,female,Garowe,3,97.0,No,No,0,52.0,D,97.0

In [ ]:
new_df.loc[
    new_df["name"] == "Yusuf Hassan",
    "gender"
] = "Male"

In [66]:
new_df[new_df["name"] == "Yusuf Hassan"]

,student_id,name,age,gender,school,city,study_hours_per_day,attendance_percent,internet_access,parent_support,absences,exam_score,grade,attendance_percent\t
2,STU057,Yusuf Hassan,18.0,Female,female,Baidoa,2,95.0,No,No,0,50.0,D,95.0
17,STU005,Yusuf Hassan,15.0,Male,male,Mogadishu,2,71.0,No,No,14,85.0,A,71.0

In [67]:
new_df["gender"].value_counts()

gender
Female      102
Male         83
female        3
 Male         1
 Female       1
Name: count, dtype: int64

In [70]:
new_df["school"] = new_df["school"].str.strip()
new_df["school"] = new_df["school"].str.lower()

school
female    108
male       82
Name: count, dtype: int64

In [71]:
new_df.head()

,student_id,name,age,gender,school,city,study_hours_per_day,attendance_percent,internet_access,parent_support,absences,exam_score,grade,attendance_percent\t
0,STU034,Abdi Mohamed,19.0,Male,male,Baidoa,4,87.0,No,No,3,69.0,C,87.0
1,STU086,Yusuf Yusuf,22.0,Male,male,Kismayo,5,87.0,No,No,0,98.0,A,87.0
2,STU057,Yusuf Hassan,18.0,Female,female,Baidoa,2,95.0,No,No,0,50.0,D,95.0
3,STU105,Hodan Yusuf,20.0,Female,female,Garowe,5,84.0,No,Yes,6,54.0,D,84.0
4,STU121,Ifrah Warsame,17.0,Male,male,Mogadishu,3,70.0,Yes,Yes,7,90.0,A,70.0

In [73]:
new_df.shape

(190, 14)

In [75]:
new_df.to_csv("cleaned student_data.csv", index=False)